# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 400)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("background: rgb(65, 65, 65)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ImportPhoto = QtWidgets.QPushButton(self.centralwidget)
        self.ImportPhoto.setGeometry(QtCore.QRect(0, 0, 251, 81))
        self.ImportPhoto.setStyleSheet("QPushButton{\n"
"  color: white;                     \n"
"  background-color: rgb(15,15,15);  \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 14px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}")
        self.ImportPhoto.setObjectName("ImportPhoto")
        self.US = QtWidgets.QPushButton(self.centralwidget)
        self.US.setGeometry(QtCore.QRect(0, 350, 41, 23))
        self.US.setStyleSheet("QPushButton{\n"
"  color: white;                     \n"
"  background-color: rgb(15,15,15);  \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 14px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}")
        self.US.setObjectName("US")
        self.RU = QtWidgets.QPushButton(self.centralwidget)
        self.RU.setGeometry(QtCore.QRect(0, 320, 41, 23))
        self.RU.setStyleSheet("QPushButton{\n"
"  color: white;                     \n"
"  background-color: rgb(15,15,15);  \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 14px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}")
        self.RU.setObjectName("RU")
        self.AI = QtWidgets.QPushButton(self.centralwidget)
        self.AI.setGeometry(QtCore.QRect(0, 180, 251, 91))
        self.AI.setStyleSheet("QPushButton{\n"
"  color: white;                     \n"
"  background-color: rgb(15,15,15);  \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 14px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}")
        self.AI.setObjectName("AI")
        self.Help = QtWidgets.QPushButton(self.centralwidget)
        self.Help.setGeometry(QtCore.QRect(530, 340, 61, 31))
        self.Help.setStyleSheet("QPushButton{\n"
"  color: white;                     \n"
"  background-color: rgb(15,15,15);  \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 14px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}")

        self.YourFolder = QtWidgets.QPushButton(self.centralwidget)
        self.YourFolder.setGeometry(QtCore.QRect(0, 90, 251, 81))
        self.YourFolder.setStyleSheet("QPushButton{\n"
"  color: white;                     \n"
"  background-color: rgb(15,15,15);  \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 14px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}")
        self.YourFolder.setObjectName("YourFolder")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(480, 0, 121, 281))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 119, 279))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Manga_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Manga_2.setGeometry(QtCore.QRect(0, 0, 70, 17))
        self.Manga_2.setStyleSheet("QCheckBox{\n"
"  color: white;                     \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 12px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QCheckBox:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QCheckBox:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}\n"
"")
        self.Manga_2.setObjectName("Manga_2")
        self.Manga_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Manga_3.setGeometry(QtCore.QRect(0, 20, 111, 17))
        self.Manga_3.setStyleSheet("QCheckBox{\n"
"  color: white;                     \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 12px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QCheckBox:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QCheckBox:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}\n"
"")
        self.Manga_3.setObjectName("Manga_3")
        self.Manga_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Manga_4.setGeometry(QtCore.QRect(0, 40, 91, 17))
        self.Manga_4.setStyleSheet("QCheckBox{\n"
"  color: white;                     \n"
"  width: 75px;                   \n"
"  height: 50px;                  \n"
"  font-size: 12px;                  \n"
"  font-weight: bold;               \n"
"  border: none;                     \n"
"  text-align: center;              \n"
"}\n"
"QCheckBox:hover {\n"
"  background-color: rgb(40,40,40);  \n"
"}\n"
"QCheckBox:pressed {\n"
"  background-color: rgb(60,60,60);  \n"
"}\n"
"")
        self.Manga_4.setObjectName("Manga_4")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoAISort"))
        self.ImportPhoto.setText(_translate("MainWindow", "ImportPhoto"))
        self.US.setText(_translate("MainWindow", "US"))
        self.RU.setText(_translate("MainWindow", "RU"))
        self.AI.setText(_translate("MainWindow", "AI"))
        self.Help.setText(_translate("MainWindow", "help"))
        self.YourFolder.setText(_translate("MainWindow", "To which folder save ?"))
        self.Manga_2.setText(_translate("MainWindow", "Манга"))
        self.Manga_3.setText(_translate("MainWindow", "Для рисунков"))
        self.Manga_4.setText(_translate("MainWindow", "Обои"))
